# GitHub Labeler Configuration
# Automatically adds labels to PRs based on changed files

# Backend changes
backend:
  - gerdsen_ai_server/**/*
  - requirements*.txt
  - setup.py
  - pyproject.toml

# Frontend changes
frontend:
  - impetus-dashboard/**/*
  - package.json
  - pnpm-lock.yaml
  - tsconfig.json

# Documentation
documentation:
  - '*.md'
  - docs/**/*
  - LICENSE

# CI/CD
ci/cd:
  - .github/**/*
  - .dockerignore
  - Dockerfile
  - docker-compose.yml

# Installers
installer:
  - installers/**/*
  - install.sh

# Configuration
configuration:
  - .env*
  - config/**/*
  - '*.yml'
  - '*.yaml'
  - '*.toml'

# Tests
tests:
  - '**/tests/**/*'
  - '**/test_*.py'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'

# Dependencies
dependencies:
  - requirements*.txt
  - package.json
  - pnpm-lock.yaml
  - Pipfile
  - Pipfile.lock
  - poetry.lock
  - pyproject.toml

# Security
security:
  - '**/auth/**/*'
  - '**/security/**/*'
  - .github/workflows/security*.yml

# Performance
performance:
  - '**/inference/**/*'
  - '**/model_loaders/**/*'
  - '**/benchmark*.py'
  - .github/workflows/performance.yml

# API changes
api:
  - '**/routes/**/*'
  - '**/schemas/**/*'
  - '**/openai_api.py'